Add macos-min-version flag

diff --git a/.github/workflows/bazel.yaml b/.github/workflows/bazel.yaml
--- a/.github/workflows/bazel.yaml
+++ b/.github/workflows/bazel.yaml
@@ -30,5 +30,14 @@ jobs:
           echo
           echo "::group::Running $(head -n1 README.md) without Nix"
           bazel build -s :hello
-          bazel-bin/hello
+          vtool -show-build bazel-bin/hello
+          bazel-bin/hello || echo "failed"
+
+          cp BUILD.mac BUILD
+
+          bazel build -s :hello
+          vtool -show-build bazel-bin/hello
+          bazel-bin/hello || echo "failed"
+
+
 
