Only build with macos_minimum_os

diff --git a/.github/workflows/bazel.yaml b/.github/workflows/bazel.yaml
--- a/.github/workflows/bazel.yaml
+++ b/.github/workflows/bazel.yaml
@@ -29,9 +29,9 @@ jobs:
         run: |
           echo
           echo "::group::Running $(head -n1 README.md) without Nix"
-          bazel build -s :hello
-          vtool -show-build bazel-bin/hello
-          bazel-bin/hello || echo "failed"
+          #bazel build -s :hello
+          #vtool -show-build bazel-bin/hello
+          #bazel-bin/hello || echo "failed"
 
           bazel build -s --macos_minimum_os=12.0 :hello
 
